<?hh // strict

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// Source: exampleany.proto

class AnyTest implements \Protobuf\Message {
  public ?\google\protobuf\Any $any;

  public function __construct() {
    $this->any = null;
  }

  public function MergeFrom(\Protobuf\Internal\Decoder $d): void {
    while (!$d->isEOF()){
      list($fn, $wt) = $d->readTag();
      switch ($fn) {
        case 1:
          if ($this->any == null) $this->any = new \google\protobuf\Any();
          $this->any->MergeFrom($d->readDecoder());
          break;
        default:
          $d->skipWireType($wt);
      }
    }
  }

  public function WriteTo(\Protobuf\Internal\Encoder $e): void {
    $msg = $this->any;
    if ($msg != null) {
      $nested = new \Protobuf\Internal\Encoder();
      $msg->WriteTo($nested);
      $e->writeEncoder($nested, 1);
    }
  }

  public function WriteJsonTo(\Protobuf\Internal\JsonEncoder $e): void {
    $e->writeMessage('any', 'any', $this->any, false);
  }

  public function MergeJsonFrom(mixed $m): void {
    if ($m === null) return;
    $d = \Protobuf\Internal\JsonDecoder::readObject($m);
    foreach ($d as $k => $v) {
      switch ($k) {
        case 'any':
          if ($v === null) break;
          if ($this->any == null) $this->any = new \google\protobuf\Any();
          $this->any->MergeJsonFrom($v);
          break;
      }
    }
  }
}


class XXX_FileDescriptor_exampleany__proto implements \Protobuf\Internal\FileDescriptor {
  const string NAME = 'exampleany.proto';
  const string RAW = 'eNo8zsFKAzEQxvGZzJisXyvqoGJFpfQgnlKsT7BXj+ILbCH2UpOiFczZF5ftsh5/fPOHwVn66T5229TlGnefZV9uZptSNtu0PGj9/b78nxZPCG2ub+lrbw+QLtdrnvPjZHURhyaOTWxzfe0PXn4Z3pSoYTTgqQmR4RhOyMSFBQxOydRTwys/b3ONACBKbOKbU0ygSo5MgrvHCY56qGlw/hzTgb4fL0exSbiajRKTcHu39ofHnv8CAAD//8IRKIs';
  public function Name(): string {
    return self::NAME;
  }

  public function FileDescriptorProtoBytes(): string {
    return (string)\gzuncompress(\base64_decode(self::RAW));
  }
}
