<?hh // strict
namespace google\protobuf;

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// Source: empty.proto

class pb_Empty implements \Protobuf\Message {

  public function __construct() {
  }

  public function MergeFrom(\Protobuf\Internal\Decoder $d): void {
    while (!$d->isEOF()){
      list($fn, $wt) = $d->readTag();
      switch ($fn) {
        default:
          $d->skipWireType($wt);
      }
    }
  }

  public function WriteTo(\Protobuf\Internal\Encoder $e): void {
  }

  public function WriteJsonTo(\Protobuf\Internal\JsonEncoder $e): void {
  }

  public function MergeJsonFrom(mixed $m): void {
    if ($m === null) return;
    $d = \Protobuf\Internal\JsonDecoder::readObject($m);
    foreach ($d as $k => $v) {
      switch ($k) {
      }
    }
  }
}


class XXX_FileDescriptor_empty__proto implements \Protobuf\Internal\FileDescriptor {
  const string NAME = 'empty.proto';
  const string RAW =
  'eNri4k7NLSip1Csoyi/JF+JPz89Pz0mF8JJK05TYuVhdQfJOZVzCyfm5emjyTlxg2QAQN4'
  .'AxSj09sySjNEkvOT9XPz0/JzEvXR+mUr+gpLIgtVgfbNsPRsZFTMzuAU6rmOTcISYGQNXp'
  .'hafm5Hjn5ZfnhYDUJ7GBDTAGBAAA//9McTwG';
  public function Name(): string {
    return self::NAME;
  }

  public function FileDescriptorProtoBytes(): string {
    return (string)\gzuncompress(\base64_decode(self::RAW));
  }
}
