<?hh // strict
namespace google\protobuf;

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// Source: empty.proto

class pb_Empty implements \Protobuf\Message {

  public function __construct() {
  }

  public function MergeFrom(\Protobuf\Internal\Decoder $d): void {
    while (!$d->isEOF()){
      list($fn, $wt) = $d->readTag();
      switch ($fn) {
        default:
          $d->skipWireType($wt);
      }
    }
  }

  public function WriteTo(\Protobuf\Internal\Encoder $e): void {
  }

  public function WriteJsonTo(\Protobuf\Internal\JsonEncoder $e): void {
  }

  public function MergeJsonFrom(mixed $m): void {
    if ($m === null) return;
    $d = \Protobuf\Internal\JsonDecoder::readObject($m);
    foreach ($d as $k => $v) {
      switch ($k) {
      }
    }
  }
}


class XXX_FileDescriptor_empty__proto implements \Protobuf\Internal\FileDescriptor {
  const string NAME = 'empty.proto';
  const string RAW =
  'eNqklk1v48YZxyXRtozJpk2ZoCk2qPvEm117E60cZC/FLlqAkkbWpDLJkpQd97QUOZJYSB'
  .'x2ZuStEOTL9NZ+i977PXrstUAvxTMzfskWQQ/xxfxr/vN7XuYBZsh7fNPoXb+RQgv/p0sh'
  .'lmtu1Xy7OO6SfYrrgxvyYSE2/XfWB8Ssxijj9h9OlpVebef9QmzOlmKd18uzW+dZo3cNV2'
  .'cm2r/b7b90vPN48LfO0bklxs7Xv+Lr9e9q8bbO0P/1Xz8iB/7eUevlB+Qfj0j7ke8dtfyv'
  .'/v4IzIZCrGGwXSy4VPACLOpEQZnrHKpac1ms8nrJYSHkJtcEhqLZyWq50vDVl1/+2m0AVh'
  .'d9gGC9BrOmQHLF5Q0v+wRWWjfq1dlZyW/4WjRcqtseYJGNS+LF3CZxRggkvKyUltV8qytR'
  .'Q16XsFUcqhqU2MqCm1/mVZ3LnclL9eBtpVcgpPkvtprARpTVoipyJPQglxwaLjeV1ryERo'
  .'qbquQl6FWuQa+wuvVavK3qJRSiLivcpHATgQ3XrwgB/Pv8ncQUiMVtRoUoOWy2SoPkOq9q'
  .'Q83n4gaXXMcI1EJXBe+BXlUK1pXSSHgYsS7fSaesVLHOqw2X/R9Koqof9uI2iUaKclvw+z'
  .'zIfSI/Kg8CrrpSFNsNr3V+e0hnQoLQKy5hk2suq3yt7lttDkivOIGH2d8VFfLK7ERwnW84'
  .'JvRwtmpxv2b6XmmFFdUWJaSCTb6DOcdJKUEL4HUppOI4FI0UG6E52J5oBSWX1Q0vYSHFht'
  .'guKLHQb3FM3ASBaniBEwSNrHCwJM5ObadIKZM7gWzCUkijcXYVJBRYCnESXbIRHcHgGrIJ'
  .'hWEUXyfsfJLBJJqOaJJCEI5gGIVZwgazLEpSAsdBCiw9NitBeA30mzihaQpRAuwinjI6gq'
  .'sgSYIwYzTtAQuH09mIhec9GMwyCKOMwJRdsIyOIIt6Juz/7oNoDBc0GU6CMAsGbMqyaxNw'
  .'zLIQg42jhEAAcZBkbDibBgnEsySOUgpY2Yilw2nALuioDyyEMAJ6ScMM0kkwnX6/UALRVU'
  .'gTzP5hmTCgMGXBYEoxlKlzxBI6zLCg+68hG9EwC6Y9AmlMhyyY9oB+Qy/iaZBc9xw0pb+f'
  .'0TBjwRRGwUVwTlM4/X9diZNoOEvoBWYdjSGdDdKMZbOMwnkUjUyzU5pcsiFNX8M0Sk3DZi'
  .'ntERgFWWBCx0k0Zln6Gr8Hs5SZxrEwo0kyizMWhc9hEl3RS5rAMJildGQ6HIVYLc4KjZJr'
  .'xGIfzAn04GpCswlNsKmmWwG2Ic0SNswe2qIEsijJyIM6IaTnU3ZOwyHF5QgxVyylzyFIWI'
  .'oGZgLDVXAN0cxUjQc1Symx3w9Gt2fOE9gYgtElw8ydO47SlLlxMW0bTlzP+4QcknbH9+Dw'
  .'Y/w69L3j1mvyHtk7/Ge3ZcUjso+i43vH3Y/J++TAqJaVPyFdK9tWO3PX944fv3LEJ63fOm'
  .'LbCmvCsE+6P3PENhJRWmLbEFE7c9f3nnz0G0f8rNVzxI4V1tRB1f3QETtIRGmJHUNE7cxd'
  .'3/vs51844tPWF47oWWFNXsf3nnY/cUQPiSgt0TNE1M7c9b2nR5874rPWsSPuWWFNex3fe9'
  .'Z97Ih7SERpiXuGiNqZPd979stPHfGk9akj7lthTfsd3zvp/sIR95GI0hL3DRG1M3d97+QT'
  .'cMTT1q8c8cAKazro+N7p3VkfIPH07qwPDPH07qwPPN87fXxE/tMhnb2W771sffD4Xx0IYM'
  .'lrLqsCzFMHNlypfMntbb0TWyjyGiR/gW8CLSC/EVUJJV9Utbmpts0a731eku/vNzflTmwl'
  .'BDFTfQhA75qqyNfA/5xvmjWHSiHPPDU05MpcOJL/acuVJuAuIMlVI2qMvGvMLZXXyMN3wk'
  .'qUfRgLCVWtdF4X/PbhgE+hquAwFgK+tT8ByKaAQS5P33kP9s1z8Dk+I7ayVvAD668t5ju8'
  .'g1Ycvk6j0Fz6XN3dyAsh4Y1xv8HKbC+MUcz/yAsNb7797k2fEEK8PTyXl4fvzw9MmJf/DQ'
  .'AA//9CKO5o';
  public function Name(): string {
    return self::NAME;
  }

  public function FileDescriptorProtoBytes(): string {
    return (string)\gzuncompress(\base64_decode(self::RAW));
  }
}
